// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5UZIECKoh4ZBwqU_7jX-zHDR8VX3B5AA',
    appId: '1:246014624491:web:6234bc8663758d46d4b4ae',
    messagingSenderId: '246014624491',
    projectId: 'gin-firebase-backend-12925',
    authDomain: 'gin-firebase-backend-12925.firebaseapp.com',
    storageBucket: 'gin-firebase-backend-12925.firebasestorage.app',
    measurementId: 'G-RNY4XEFZG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA45TlouZf1jo74U7eh-PFasRvVtPbNGk8',
    appId: '1:246014624491:android:c674e3626638c64cd4b4ae',
    messagingSenderId: '246014624491',
    projectId: 'gin-firebase-backend-12925',
    storageBucket: 'gin-firebase-backend-12925.firebasestorage.app',
  );
}
